### ISSUE TITLE
Error on an old device ? 

### ISSUE THREAD

**Issue by arielkuma** [Cyr-ius/hass-heatzy#16]
Hi 

I've got an old device (no lock in the app and can't group it in heatzy app) 

since the last update can't control from HA 

here are the logs if any help : 

Logger: homeassistant.core
Source: custom_components/heatzy/climate.py:115 
Integration: Heatzy (documentation, issues) 
First occurred: 18:20:00 (3 occurrences) 
Last logged: 18:22:20

Error executing service: <ServiceCall homeassistant.turn_off (c:0fe37c73f17271f4fc771d77133f7ac2): entity_id=['switch.chauffage_coin']>
Error executing service: <ServiceCall homeassistant.turn_on (c:ff2114a420c7a2aa927ebe527649f213): entity_id=['switch.chauffage_coin']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1511, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 121, in async_handle_turn_service
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/template/switch.py", line 190, in async_turn_off
    await self._off_script.async_run(context=self._context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1260, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/heatzy/climate.py", line 115, in async_set_preset_mode
    await self.coordinator.heatzy_client.control_device(
AttributeError: 'HeatzyClient' object has no attribute 'control_device'

**Comment by bikerman51** [comment]
I’ve the same problem

**Comment by arielkuma** [comment]
had to revert back to 4.6 to be able to control each heatzy

**Comment by Cyr-ius** [comment]
Fix with 5.3
