### ISSUE TITLE
Error in logs with heatzy gow and pilote

### ISSUE THREAD

**Issue by cob94440** [cyr-ius/hass-heatzy#37]
Hello, I have those errors in log :

```2023-05-07 20:18:46.625 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform heatzy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 634, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 297, in state_attributes
    self.current_temperature,
  File "/config/custom_components/heatzy/climate.py", line 209, in current_temperature
    return (cur_tempL + (cur_tempH * 255)) / 10
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
2023-05-07 20:18:46.629 ERROR (MainThread) [homeassistant.components.climate] Error while setting up heatzy platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 312, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 634, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 297, in state_attributes
    self.current_temperature,
  File "/config/custom_components/heatzy/climate.py", line 209, in current_temperature
    return (cur_tempL + (cur_tempH * 255)) / 10
```
And sometimes i have to reload the integration to have my climate back.
I'm on 2023.4.6 and heatzy 5.7.2

**Comment by cyr-ius** [comment]
Pleasqe update version to 5.8.5
